### ISSUE TITLE
Able to add more images then allowed

### ISSUE THREAD

**Issue by martn001** [kingscode/vuetify-upload#6]
My image uploader has a max property with value of 2. Only two images should be selectedable/allowed. When you're selecting more then two images, all will be selected.

![selecting-more-images-then-allowed](https://user-images.githubusercontent.com/8685175/59276230-34abce80-8c5e-11e9-8624-767e1192a4dd.PNG)

![after-selecting-images](https://user-images.githubusercontent.com/8685175/59276253-41c8bd80-8c5e-11e9-9721-7b051635d77a.PNG)

**Comment by ricardovanlaarhoven** [comment]
it's impossible to let the HTML input have a limit, this also is an issue when dragging them in the browser.
We should remove all items exceeding the limit.
